version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 127.0.0.1:80:80 # Serveur Nginx+Php
      - 127.0.0.1:8081:8081 # Phpmyadmin
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - php
      - phpmyadmin
    runtime: "runc"

  php:
    build:
      context: .
      dockerfile: php-dockerfile # PHP FPM
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
    runtime: "runc"

  mariadb:
    image: mariadb
    volumes:
      - mariadbdata:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
    runtime: "runc"

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    volumes:
      - phpmyadmindata:/var/www/html # Emplacement de phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb
    runtime: "runc"

volumes:
  # mariadbdata se situe dans le container mariadb /var/lyb/mysql
  mariadbdata:

  # phpmyadmindata se situe dans le container phpmyadmin /var/www/html mais également dans le container nginx /var/www/phpmyadmin
  phpmyadmindata:
